config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('omcen/', include('omcen.urls')),
    path('password box/', include('password_box.urls')),
    path('file encryption/', include('file_encryption.urls')),
    path('tango/', include('tango.urls')),
    path('portfolio/', include('portfolio.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

omcen/urls.py
from django.urls import path

from omcen.views import ServiceControl, CreateService, ServiceList, ServiceSubscribe, PlanSelection, ServiceInUseList, \
    ServiceUnsubscribe, switching_enabled, ServiceDetail, CreatePlan, UpdatePlan, DeletePlan, OmcenUserDeactivate, \
    MyPage, ChangeProfile, LinkingOmcenUsersToSocialAccountsView, LinkedIDPublishing, LinkingUser, Top

app_name = 'Omcen'

urlpatterns = [
    # 管理画面
    path('admin/service_control/', ServiceControl.as_view(), name='service_control'),

    # サービスCRUD
    path('admin/service_detail/<uuid:service_id>/', ServiceDetail.as_view(), name='service_detail'),
    path('admin/create_service', CreateService.as_view(), name='create_service'),
    # path('admin/update_service/<int:pk>', , name='update_service'),
    # path('admin/delete_service/<int:pk>', , name='delete_service'),

    # プランCRUD
    path('admin/create_plan/<uuid:service_id>/', CreatePlan.as_view(), name="create_plan"),
    path('admin/update_plan/<uuid:service_id>/<uuid:pk>/', UpdatePlan.as_view(), name="update_plan"),
    path('admin/delete_plan/<uuid:service_id>/<uuid:pk>/', DeletePlan.as_view(), name="delete_plan"),

    # サービスの有効無効切り替え
    path('admin/switching_enabled/<uuid:service_id>/<uuid:plan_id>/<str:flag>/', switching_enabled,
         name='switching_enabled'),

    # サービス一覧
    path('service_list/', ServiceList.as_view(), name='service_list'),
    # プラン選択
    path('<str:service_name>/plan_selection/', PlanSelection.as_view(), name='plan_selection'),
    # サービス登録
    path('<uuid:pk>/service_subscribe/', ServiceSubscribe.as_view(), name='service_subscribe'),
    # サービス登録解除
    path('<uuid:pk>/service_unsubscribe/', ServiceUnsubscribe.as_view(), name='service_unsubscribe'),
    # 登録中のサービス一覧
    path('service_in_use_list/', ServiceInUseList.as_view(), name='service_in_use_list'),

    # omcenユーザの停止
    path('<uuid:pk>/omcen_user_deactivate/', OmcenUserDeactivate.as_view(), name='omcen_user_deactivate'),
    # マイページ
    path('my_page/', MyPage.as_view(), name='my_page'),
    # プロフィール編集
    path('my_page/<uuid:pk>/change_profile/', ChangeProfile.as_view(), name='change_profile'),
    # 連携ID発行
    path('account_linking/linked_id_publishing/', LinkedIDPublishing.as_view(), name='linked_id_publishing'),
    # ソーシャルアカウントの連携一覧
    path('account_linking/linking_omcen_users_to_social_accounts/', LinkingOmcenUsersToSocialAccountsView.as_view(),
         name='linking_omcen_users_to_social_accounts'),
    # User連携
    path('account_linking/linking_user/', LinkingUser.as_view(), name='linking_user'),
    
    # Top
    path('top/', Top.as_view(), name='top'),
]

tango/urls.py
# -*- coding: utf-8 -*-
"""
Created on 2021/12/05 13:56:15

@author: cobalt
"""

from django.urls import path

from tango.views import TopView, VocabularyNotebookCreateView, VocabularyNotebookDeleteView, \
    VocabularyNotebookUpdateView, VocabularyNotebookReadView, TangoCreateView, TangoReadView, TangoUpdateView, \
    TangoDeleteView

app_name = 'Tango'

urlpatterns = [
    # 単語帳トップページ
    path('top/', TopView.as_view(), name='top'),
    # 単語帳CRUD
    path('vocabulary_notebook_create/', VocabularyNotebookCreateView.as_view(), name='vocabulary_notebook_create'),
    path('<uuid:pk>/vocabulary_notebook_read/', VocabularyNotebookReadView.as_view(), name='vocabulary_notebook_read'),
    path('<uuid:pk>/vocabulary_notebook_update/', VocabularyNotebookUpdateView.as_view(),
         name='vocabulary_notebook_update'),
    path('<uuid:pk>/vocabulary_notebook_delete/', VocabularyNotebookDeleteView.as_view(),
         name='vocabulary_notebook_delete'),
    # 単語CRUD
    path('<uuid:vocabulary_notebook_pk>/tango/tango_create/', TangoCreateView.as_view(), name='tango_create'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_read/', TangoReadView.as_view(), name='tango_read'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_update/', TangoUpdateView.as_view(), name='tango_update'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_delete/', TangoDeleteView.as_view(), name='tango_delete'),
]

tango/models.py
import uuid as uuid_lib

from django.db import models

from accounts.models import OmcenUser


class VocabularyNotebook(models.Model):
    class Meta:
        verbose_name = '単語帳'
        verbose_name_plural = '単語帳'
        constraints = [
            models.UniqueConstraint(
                fields=['omcen_user', 'vocabulary_notebook_name'],
                name="vocabulary_notebook_unique"
            ),
        ]

    uuid = models.UUIDField(
        default=uuid_lib.uuid4,
        primary_key=True,
        editable=False
    )

    omcen_user = models.ForeignKey(
        OmcenUser,
        on_delete=models.CASCADE
    )

    vocabulary_notebook_name = models.CharField(
        '単語帳',
        max_length=64,
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(
        '作成日時',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        '更新日時',
        auto_now=True
    )


class Tango(models.Model):
    class Meta:
        verbose_name = '単語'
        verbose_name_plural = '単語'
        constraints = [
            models.UniqueConstraint(
                fields=['vocabulary_notebook', 'tango'],
                name="tango_unique"
            ),
        ]

    uuid = models.UUIDField(
        default=uuid_lib.uuid4,
        primary_key=True,
        editable=False
    )
    vocabulary_notebook = models.ForeignKey(
        VocabularyNotebook,
        on_delete=models.CASCADE
    )

    tango = models.CharField(
        '単語',
        max_length=64,
        blank=True,
        null=True
    )
    contents = models.CharField(
        '内容',
        max_length=8192,
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(
        '作成日時',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        '更新日時',
        auto_now=True
    )

tango/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import IntegrityError
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, TemplateView

from omcen.models import ServiceInUse
from tango.forms import VocabularyNotebookCreateForm, VocabularyNotebookUpdateForm, TangoCreateForm, TangoUpdateForm, \
    TangoSearchForm, VocabularyNotebookSearchForm
from tango.models import VocabularyNotebook, Tango


# トップページ
class TopView(LoginRequiredMixin, ListView):
    template_name = 'tango/top.html'
    model = VocabularyNotebook
    paginate_by = 30
    ordering = '-created_at'

    def __init__(self):
        super().__init__()
        self.form = VocabularyNotebookSearchForm()

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not ServiceInUse.objects.filter(
                omcen_user__username=self.request.user,
                omcen_service__service__service_name__icontains='Tango',
                is_active=True
        ).exists():
            messages.warning(self.request, _('Tangoサービスを登録していません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:plan_selection', kwargs={'service_name': 'Tango'}))

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        self.form = VocabularyNotebookSearchForm(self.request.GET or None)

        query_set = query_set.filter(
            omcen_user__username=self.request.user,
        )

        if self.form.is_bound:
            if self.form.is_valid():
                if self.form.cleaned_data['vocabulary_notebook_name']:
                    if self.form.cleaned_data['search_type'] == '0':
                        query_set = query_set.filter(
                            vocabulary_notebook_name__icontains=self.form.cleaned_data['vocabulary_notebook_name'],
                        )
                    else:
                        query_set = query_set.filter(
                            vocabulary_notebook_name=self.form.cleaned_data['vocabulary_notebook_name'],
                        )

                if not query_set.exists():
                    messages.info(self.request, _('該当する単語帳がありませんでした。'), extra_tags='info')

        return query_set.order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = self.form

        if 'vocabulary_notebook_name' in self.request.GET:
            context['vocabulary_notebook_name'] = self.request.GET['vocabulary_notebook_name']
            context['search_type'] = self.request.GET['search_type']
        else:
            context['vocabulary_notebook_name'] = ''
            context['search_type'] = 0

        return context


# 単語帳CRUD
class VocabularyNotebookCreateView(LoginRequiredMixin, CreateView):
    template_name = 'tango/vocabulary_notebook_create.html'
    model = VocabularyNotebook
    form_class = VocabularyNotebookCreateForm
    success_url = reverse_lazy('Tango:top')

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not ServiceInUse.objects.filter(
                omcen_user__username=self.request.user,
                omcen_service__service__service_name__icontains='Tango',
                is_active=True
        ).exists():
            messages.warning(self.request, _('Tangoサービスを登録していません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:plan_selection', kwargs={'service_name': 'Tango'}))

        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            if VocabularyNotebook.objects.filter(
                    omcen_user=self.request.user,
                    vocabulary_notebook_name=form.cleaned_data['vocabulary_notebook_name']).exists():
                messages.warning(self.request, _('同じ単語帳名が存在します。'), extra_tags='warning')
                return super().form_invalid(form)
            form.instance.omcen_user = self.request.user
            form.instance.vocabulary_notebook_name = form.cleaned_data['vocabulary_notebook_name']

        return super().form_valid(form)


class VocabularyNotebookReadView(LoginRequiredMixin, ListView):
    template_name = 'tango/vocabulary_notebook_read.html'
    model = Tango
    paginate_by = 30
    ordering = '-created_at'

    def __init__(self):
        super().__init__()
        self.form = TangoSearchForm()

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not ServiceInUse.objects.filter(
                omcen_user__username=self.request.user,
                omcen_service__service__service_name__icontains='Tango',
                is_active=True
        ).exists():
            messages.warning(self.request, _('Tangoサービスを登録していません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:plan_selection', kwargs={'service_name': 'Tango'}))

        if not VocabularyNotebook.objects.filter(
                omcen_user__username=self.request.user,
                uuid=self.request.resolver_match.kwargs['pk']
        ).exists():
            messages.warning(self.request, _('単語帳が存在しません'), extra_tags='warning')

            return redirect(to=reverse('Tango:top'))

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        self.form = TangoSearchForm(self.request.GET or None)

        query_set = query_set.filter(
            vocabulary_notebook=get_object_or_404(VocabularyNotebook, omcen_user__username=self.request.user,
                                                  uuid=self.request.resolver_match.kwargs['pk'])
        )

        if self.form.is_bound:
            if self.form.is_valid():
                if self.form.cleaned_data['tango']:
                    tango = 'tango'
                    contents = 'contents'

                    tango_q = Q(**{tango: self.form.cleaned_data['tango']})
                    contents_q = Q()

                    if self.form.cleaned_data['search_type'] == '0':
                        tango += '__icontains'
                        tango_q = Q(**{tango: self.form.cleaned_data['tango']})

                        contents += '__icontains'

                    if self.form.cleaned_data['search_scope'] == '1':
                        contents_q = Q(**{contents: self.form.cleaned_data['tango']})

                    query_set = query_set.filter(
                        tango_q
                        |
                        contents_q
                    ).distinct()

                if not query_set.exists():
                    messages.info(self.request, _('該当する単語がありませんでした。'), extra_tags='info')

        return query_set.order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = self.form
        context['vocabulary_notebook_uuid'] = self.request.resolver_match.kwargs['pk']
        context['vocabulary_notebook_name'] = get_object_or_404(
            VocabularyNotebook,
            omcen_user__username=self.request.user,
            uuid=self.request.resolver_match.kwargs['pk'],
        ).vocabulary_notebook_name

        if 'tango' in self.request.GET:
            context['tango'] = self.request.GET['tango']
            context['search_type'] = self.request.GET['search_type']
            context['search_scope'] = self.request.GET['search_scope']
        else:
            context['tango'] = ''
            context['search_type'] = 0
            context['search_scope'] = 0

        return context


class VocabularyNotebookUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'tango/vocabulary_notebook_update.html'
    model = VocabularyNotebook
    form_class = VocabularyNotebookUpdateForm
    success_url = reverse_lazy('Tango:top')

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not ServiceInUse.objects.filter(
                omcen_user__username=self.request.user,
                omcen_service__service__service_name__icontains='Tango',
                is_active=True
        ).exists():
            messages.warning(self.request, _('Tangoサービスを登録していません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:plan_selection', kwargs={'service_name': 'Tango'}))

        if not VocabularyNotebook.objects.filter(
                omcen_user__username=self.request.user,
                uuid=self.request.resolver_match.kwargs['pk']
        ).exists():
            messages.warning(self.request, _('単語帳が存在しません'), extra_tags='warning')

            return redirect(to=reverse('Tango:top'))

        return super().dispatch(self.request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(VocabularyNotebookUpdateView, self).get_form_kwargs()

        kwargs['vocabulary_notebook_name'] = get_object_or_404(
            VocabularyNotebook,
            omcen_user__username=self.request.user,
            uuid=self.request.resolver_match.kwargs['pk'],

templates/tango/base.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block app_name %}
<a class="navbar-brand" href="{% url 'Tango:top' %}">
    <h2>Tango</h2>
</a>
{% endblock %}

{% block nav_item %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'Tango:top' %}">
        {% trans "トップ" %}
    </a>
</li>
{% endblock %}

templates/tango/tango_create.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語　新規作成" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{% trans "単語　新規作成" %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.tango }}
                    <br><br>
                    {{ form.contents }}
                    <br>
                    <nobr class="float-end">
                        <button class="btn btn-primary me-3" type="submit">
                            {% trans "新規作成" %}
                        </button>
                        <a class="btn btn-secondary" role="button"
                           href="{% url 'Tango:vocabulary_notebook_read' pk=vocabulary_notebook_uuid %}">
                            {% trans "キャンセル" %}
                        </a>
                    </nobr>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/tango_delete.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語　削除" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{% trans "単語　削除" %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>
                    {% blocktrans %}
                    {{ tango }}を削除しますか？
                    {% endblocktrans %}
                </p>
                <a class="btn btn-secondary float-end" role="button"
                   href="{% url 'Tango:vocabulary_notebook_read' pk=vocabulary_notebook_uuid %}">
                    {% trans "キャンセル" %}
                </a>
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger float-end me-3" type="submit">
                        {% trans "削除" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/tango_pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
               href="?tango={{ tango }}&search_type={{ search_type }}&search_scope={{ search_scope }}&page={{ page_obj.previous_page_number }}"
               aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for num in paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">
            {{ num }}
            </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link"
               href="?tango={{ tango }}&search_type={{ search_type }}&search_scope={{ search_scope }}&page={{ num }}">
                {{ num }}
            </a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
               href="?tango={{ tango }}&search_type={{ search_type }}&search_scope={{ search_scope }}&page={{ page_obj.next_page_number }}"
               aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

templates/tango/tango_read.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{{ tango.tango }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{{ tango.tango }}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div width="100%">{{ tango.contents }}</div>
                <br>
                <a class="btn btn-secondary float-end" role="button"
                   href="{% url 'Tango:vocabulary_notebook_read' pk=vocabulary_notebook_uuid %}">
                    {% trans "戻る" %}
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/tango_update.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語　編集" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{% trans "単語　編集" %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.tango }}
                    <br><br>
                    {{ form.contents }}
                    <br>
                    <nobr class="float-end">
                        <button class="btn btn-info me-3" type="submit">
                            {% trans "編集" %}
                        </button>
                        <a class="btn btn-secondary" role="button"
                           href="{% url 'Tango:vocabulary_notebook_read' pk=vocabulary_notebook_uuid %}">
                            {% trans "キャンセル" %}
                        </a>
                    </nobr>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/top.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語帳" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-primary text-white">
        <div class="row">
            <div class="col">
                <h1>{% trans "単語帳" %}</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form class="row">
            <nobr>
                {{ form.vocabulary_notebook_name }}
                {{ form.search_type }}
                <button type="submit" class="btn btn-success float-end">
                    {% trans "検索" %}
                </button>
            </nobr>
        </form>
    </div>
    <div class="card-footer">
        <a class="primaryAction btn btn-primary float-end" role="button"
           href="{% url 'Tango:vocabulary_notebook_create' %}">
            {% trans "新規作成" %}
        </a>
    </div>
</div>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for vocabulary_notebook in object_list %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h2 class="text-truncate">{{ vocabulary_notebook.vocabulary_notebook_name }}</h2>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <nobr class="float-end">
                    <a class="btn btn-sm btn-primary me-1"
                       href="{% url 'Tango:vocabulary_notebook_read' pk=vocabulary_notebook.uuid %}">
                        {% trans "選択" %}
                    </a>
                    <a class="btn btn-sm btn-info me-1"
                       href="{% url 'Tango:vocabulary_notebook_update' pk=vocabulary_notebook.uuid %}">
                        {% trans "名前の変更" %}
                    </a>
                    <a class="btn btn-sm btn-danger"
                       href="{% url 'Tango:vocabulary_notebook_delete' pk=vocabulary_notebook.uuid %}">
                        {% trans "削除" %}
                    </a>
                </nobr>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/tango/vocabulary_notebook_create.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語帳　新規作成" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{% trans "単語帳　新規作成" %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>{{ form.vocabulary_notebook_name }}</p>
                    <nobr class="float-end">
                        <button class="btn btn-primary me-3" type="submit">
                            {% trans "新規作成" %}
                        </button>
                        <a class="btn btn-secondary" role="button"
                           href="{% url 'Tango:top' %}">
                            {% trans "キャンセル" %}
                        </a>
                    </nobr>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/vocabulary_notebook_delete.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{% trans "Tango - 単語帳　削除" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{% trans "単語帳　削除" %}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>{{ object.vocabulary_notebook_name }}{% trans "を削除しますか？" %}</p>
                <a class="btn btn-secondary float-end" role="button"
                   href="{% url 'Tango:top' %}">
                    {% trans "キャンセル" %}
                </a>
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger float-end me-3" type="submit">
                        {% trans "削除" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/tango/vocabulary_notebook_read.html
{% extends "tango/base.html" %}

{% load i18n %}
{% load static %}
{% block head_title %}{{ vocabulary_notebook_name }}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-primary text-white">
        <div class="row">
            <div class="col">
                <h1>{{ vocabulary_notebook_name }}</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form class="row">
            <nobr>
                {{ form.tango }}
                {{ form.search_type }}
                {{ form.search_scope }}
                <button type="submit" class="btn btn-success float-end">
                    {% trans "検索" %}
                </button>
            </nobr>
        </form>
    </div>
    <div class="card-footer">
        <a class="primaryAction btn btn-primary float-end" role="button"
           href="{% url 'Tango:tango_create' vocabulary_notebook_pk=vocabulary_notebook_uuid %}">
            {% trans "単語の追加" %}
        </a>
    </div>
</div>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for tango in object_list %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h2>{{ tango.tango }}</h2>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="text-truncate">{{ tango.contents }}</div>
            </div>
            <div class="card-footer">
                <nobr class="float-end">
                    <a class="btn btn-primary btn-sm me-1"
                       href="{% url 'Tango:tango_read' vocabulary_notebook_pk=vocabulary_notebook_uuid pk=tango.uuid %}">
                        {% trans "選択" %}
                    </a>
                    <a class="btn btn-info btn-sm me-1"
                       href="{% url 'Tango:tango_update' vocabulary_notebook_pk=vocabulary_notebook_uuid pk=tango.uuid %}">
                        {% trans "単語の編集" %}
                    </a>
                    <a class="btn btn-danger btn-sm"
                       href="{% url 'Tango:tango_delete' vocabulary_notebook_pk=vocabulary_notebook_uuid pk=tango.uuid %}">
                        {% trans "削除" %}
                    </a>
                </nobr>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}