config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('omcen/', include('omcen.urls')),
    path('password box/', include('password_box.urls')),
    path('file encryption/', include('file_encryption.urls')),
    path('tango/', include('tango.urls')),
    path('portfolio/', include('portfolio.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

omcen/urls.py
from django.urls import path

from omcen.views import ServiceControl, CreateService, ServiceList, ServiceSubscribe, PlanSelection, ServiceInUseList, \
    ServiceUnsubscribe, switching_enabled, ServiceDetail, CreatePlan, UpdatePlan, DeletePlan, OmcenUserDeactivate, \
    MyPage, ChangeProfile, LinkingOmcenUsersToSocialAccountsView, LinkedIDPublishing, LinkingUser, Top

app_name = 'Omcen'

urlpatterns = [
    # 管理画面
    path('admin/service_control/', ServiceControl.as_view(), name='service_control'),

    # サービスCRUD
    path('admin/service_detail/<uuid:service_id>/', ServiceDetail.as_view(), name='service_detail'),
    path('admin/create_service', CreateService.as_view(), name='create_service'),
    # path('admin/update_service/<int:pk>', , name='update_service'),
    # path('admin/delete_service/<int:pk>', , name='delete_service'),

    # プランCRUD
    path('admin/create_plan/<uuid:service_id>/', CreatePlan.as_view(), name="create_plan"),
    path('admin/update_plan/<uuid:service_id>/<uuid:pk>/', UpdatePlan.as_view(), name="update_plan"),
    path('admin/delete_plan/<uuid:service_id>/<uuid:pk>/', DeletePlan.as_view(), name="delete_plan"),

    # サービスの有効無効切り替え
    path('admin/switching_enabled/<uuid:service_id>/<uuid:plan_id>/<str:flag>/', switching_enabled,
         name='switching_enabled'),

    # サービス一覧
    path('service_list/', ServiceList.as_view(), name='service_list'),
    # プラン選択
    path('<str:service_name>/plan_selection/', PlanSelection.as_view(), name='plan_selection'),
    # サービス登録
    path('<uuid:pk>/service_subscribe/', ServiceSubscribe.as_view(), name='service_subscribe'),
    # サービス登録解除
    path('<uuid:pk>/service_unsubscribe/', ServiceUnsubscribe.as_view(), name='service_unsubscribe'),
    # 登録中のサービス一覧
    path('service_in_use_list/', ServiceInUseList.as_view(), name='service_in_use_list'),

    # omcenユーザの停止
    path('<uuid:pk>/omcen_user_deactivate/', OmcenUserDeactivate.as_view(), name='omcen_user_deactivate'),
    # マイページ
    path('my_page/', MyPage.as_view(), name='my_page'),
    # プロフィール編集
    path('my_page/<uuid:pk>/change_profile/', ChangeProfile.as_view(), name='change_profile'),
    # 連携ID発行
    path('account_linking/linked_id_publishing/', LinkedIDPublishing.as_view(), name='linked_id_publishing'),
    # ソーシャルアカウントの連携一覧
    path('account_linking/linking_omcen_users_to_social_accounts/', LinkingOmcenUsersToSocialAccountsView.as_view(),
         name='linking_omcen_users_to_social_accounts'),
    # User連携
    path('account_linking/linking_user/', LinkingUser.as_view(), name='linking_user'),
    
    # Top
    path('top/', Top.as_view(), name='top'),
]

password_box/urls.py
# -*- coding: utf-8 -*-
"""
Created on 2021/10/25 10:36:56

@author: cobalt
"""
from django.urls import path

from password_box.views import Top, BoxCreate, BoxView, BoxDelete, BoxUpdate, BoxPasswordUpdate

app_name = 'Password Box'

urlpatterns = [
    path('top/', Top.as_view(), name='top'),
    path('<uuid:pk>/view/', BoxView.as_view(), name='view'),

    # ボックスCRUD
    path('create/', BoxCreate.as_view(), name='create'),
    path('<uuid:pk>/delete/', BoxDelete.as_view(), name='delete'),
    path('<uuid:pk>/update/', BoxUpdate.as_view(), name='update'),
    path('<uuid:pk>/update password/', BoxPasswordUpdate.as_view(), name='update_box_password'),
]

portfolio/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from portfolio.views import Top, Profile, Deliverables, VocabularyNotebook, Omcen, PasswordBox, DBPePro

app_name = 'Portfolio'

urlpatterns = [
    path('top/', Top.as_view(), name='top'),
    path('profile/', Profile.as_view(), name='profile'),
    path('deliverables/', Deliverables.as_view(), name='deliverables'),
    path('vocabulary_notebook/', VocabularyNotebook.as_view(), name='vocabulary_notebook'),
    path('omcen/', Omcen.as_view(), name='omcen'),
    path('password_box/', PasswordBox.as_view(), name='password_box'),
    path('dbpepro/', DBPePro.as_view(), name='dbpepro'),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core import validators
from django.utils.translation import gettext_lazy as _


# 文字フィールドバリエーション
class CharFieldValidator(validators.RegexValidator):
    regex = r'^[\w.@+-]+\Z'
    message = '有効な値を入力してください。この値には、数字・文字 @/./+/-/_ のみを含めることができます。'
    flags = 0


# メッセージ送信用フォーム
class EmailForm(forms.Form):
    email_title_validator = CharFieldValidator()
    email_title = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'style': 'width:100%',
            'placeholder': _('件名')
        }),
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[email_title_validator],
    )

    email_message_validator = CharFieldValidator()
    email_message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            'style': 'width:100%',
            'placeholder': _('内容')
        }),
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[email_message_validator],
    )

omcen/views.py
import datetime
import uuid as uuid_lib

import pytz
from allauth.socialaccount import providers
from allauth.socialaccount.models import SocialAccount
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView, TemplateView, DeleteView, FormView

from accounts.models import OmcenUser
# from file_encryption.models import FileEncryptionUser
from omcen.forms import SearchService, CreateServiceForm, ServiceSubscribeForm, ServiceUnsubscribeForm, CreatePlanForm, \
    UpdatePlanForm, DeletePlanForm, OmcenUserDeactivateForm, ChangeProfileForm, LinkedIDPublishingForm, LinkingUserForm
from omcen.models import Service, Plan, ServiceGroup, ServiceInUse, LinkingOmcenUsersToSocialAccounts, \
    LinkedID
from password_box.models import PasswordBoxUser, PasswordBox


# サービスの有効・無効切り替え
@login_required
def switching_enabled(request, service_id, plan_id, flag):
    service_group = get_object_or_404(ServiceGroup, service_id=service_id, plan_id=plan_id)
    if flag == 'enabled':
        service_group.is_active = True
        service_group.plan.is_active = True
        messages.success(request, 'サービスを有効にしました。')
    elif flag == 'disabled':
        service_group.is_active = False
        service_group.plan.is_active = False
        messages.success(request, 'サービスを無効にしました。')
    else:
        messages.error(request, 'サービスの有効・無効切り替えに失敗しました。')
        return redirect(reverse_lazy('Omcen:service_detail', args=[service_id]))

    with transaction.atomic():
        service_group.save()
        service_group.plan.save()

    return redirect(reverse_lazy('Omcen:service_detail', args=[service_id]))


# サービス管理画面
class ServiceControl(LoginRequiredMixin, ListView):
    template_name = 'omcen/admin_service_control.html'
    model = Service
    paginate_by = 30
    ordering = 'is_active'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'))
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        form = SearchService(self.request.GET or None)
        query_set = super().get_queryset()

        if form.is_bound:
            if form.is_valid():
                service_name = form.cleaned_data.get('service_name')

                if service_name:
                    query_set = query_set.filter(service_name__icontains=service_name)

            if not query_set.exists():
                messages.info(self.request, '該当するサービスがありませんでした。', extra_tags='info')

        return query_set.order_by('service_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchService()

        return context


# サービスの詳細画面
class ServiceDetail(LoginRequiredMixin, TemplateView):
    template_name = 'omcen/admin_service_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        context['plans'] = Plan.objects.filter(service=service)
        context['service'] = service

        return context


# サービスの新規作成
class CreateService(LoginRequiredMixin, CreateView):
    template_name = 'omcen/admin_create_service.html'
    model = ServiceGroup
    form_class = CreateServiceForm
    success_url = reverse_lazy('Omcen:service_control')

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'))
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        # サービスを追加する場合、最低でも1つプランをセットする
        with transaction.atomic():
            service = Service.objects.create(service_name=form.cleaned_data['service_name'])
            plan = Plan.objects.create(service=service,
                                       plan_name=form.cleaned_data['plan_name'],
                                       price=form.cleaned_data['price'])

        if all([service, plan]):
            form.instance.service = service
            form.instance.plan = plan
            form.instance.is_active = False

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def get_success_url(self):
        messages.success(self.request, 'サービスを新しく追加しました。', extra_tags='success')

        return super().get_success_url()


# プランの新規作成
class CreatePlan(LoginRequiredMixin, CreateView):
    template_name = 'omcen/admin_create_plan.html'
    model = Plan
    form_class = CreatePlanForm

    def form_valid(self, form):
        form.instance.service = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service'] = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        return context

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# プランの編集
class UpdatePlan(LoginRequiredMixin, UpdateView):
    template_name = 'omcen/admin_update_plan.html'
    model = Plan
    form_class = UpdatePlanForm

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# プランの削除
class DeletePlan(LoginRequiredMixin, DeleteView):
    template_name = 'omcen/admin_delete_plan.html'
    model = Plan
    form_class = DeletePlanForm

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# サービス一覧
class ServiceList(LoginRequiredMixin, ListView):
    template_name = 'omcen/service_list.html'
    model = Service
    paginate_by = 30
    ordering = 'service_name'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        query_set = query_set.filter(is_active=True)

        return query_set.order_by('service_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Service.objects.filter(is_active=True)

        services_dict = {}
        for service in services:
            if ServiceInUse.objects.filter(
                    omcen_user__username=self.request.user,
                    omcen_service__service__service_name=service.service_name
            ).exists():
                services_dict.update({
                    service.service_name: f'{service.service_name}:top'
                })
            else:
                services_dict.update({
                    service.service_name: 'Omcen:plan_selection'
                })

        context['service_dict'] = services_dict

        return context


# プラン選択画面
class PlanSelection(LoginRequiredMixin, ListView):
    template_name = 'omcen/plan_selection.html'
    model = ServiceGroup
    paginate_by = 30
    ordering = 'is_active'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not Service.objects.filter(service_name=self.request.resolver_match.kwargs['service_name']).exists():
            messages.warning(self.request, _('入力されたサービス名は存在しません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:service_list'))

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        query_set = query_set.filter(
            service__service_name=self.request.resolver_match.kwargs['service_name'],
            is_active=True
        )

        return query_set.order_by('plan__plan_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service_in_use'] = ServiceInUse.objects.filter(
            omcen_user__username=self.request.user,
            omcen_service__service__service_name=self.request.resolver_match.kwargs['service_name'],
            is_active=True
        )

        return context


# サービスの登録
class ServiceSubscribe(LoginRequiredMixin, CreateView):
    template_name = 'omcen/service_subscribe.html'
    model = ServiceInUse
    form_class = ServiceSubscribeForm

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if ServiceInUse.objects.filter(omcen_user__username=self.request.user,
                                       omcen_service__uuid=self.request.resolver_match.kwargs['pk'],
                                       is_active=True).exists():
            service_in_use = get_object_or_404(
                ServiceInUse,
                omcen_user__username=self.request.user,

templates/portfolio/base.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block app_name %}
<a class="navbar-brand" href="{% url 'Portfolio:top' %}">
    <h2>Portfolio</h2>
</a>
{% endblock %}

{% block nav_item %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'Portfolio:top' %}">
        {% trans "トップ" %}
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'Portfolio:profile' %}">
        {% trans "プロフィール" %}
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'Portfolio:deliverables' %}">
        {% trans "成果物" %}
    </a>
</li>
{% endblock %}

templates/portfolio/dbpepro.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Portfolio - DBPePro" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h1>DBPePro</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        {% blocktrans %}
        〇 なぜ、作ろうと思ったのか
        <br>
        　DBの権限管理を手動で行うのは冗長な作業なため、その解決手段として作ろうと思いました
        <br><br>
        〇 概要
        <br>
        　DBPeProの主な機能としては、対象に対して権限の付与・削除ができます
        <br>
        　DBPeProの名前の由来はラテン語訳で「データベース権限管理: Database permissio procuratio」からきています
        <br><br>
        〇 開発環境
        <br>
        　OS: Windows
        <br>
        　言語:
        <br>
        　　フロントエンド: Dart
        <br>
        　　バックエンド: Python
        <br>
        　フレームワーク:
        <br>
        　　フロントエンド: Flutter
        <br>
        　　バックエンド: FastAPI
        <br><br>
        〇 ソースコード:
        <br>
        　フロントエンド: <a href="https://github.com/cobaemon/DBPePro">GitHub</a>
        <br>
        　バックエンド: <a href="https://github.com/cobaemon/DBPeProAPI">GitHub</a>
        <br>
        〇 完成品:
        <br>
        　フロントエンド: <a href="https://github.com/cobaemon/DBPePro/releases">GitHub: releases</a>
        <br>
        　バックエンド: <a href="https://github.com/cobaemon/DBPeProAPI/releases">GitHub: releases</a>
        <br><br>
        〇 工夫
        <br>
        　フロントエンドにDart/Flutterを使うことで、Pythonの苦手な部分をカバーしました
        <br><br>
        〇 利用方法
        <br>
        　フロントエンド: <a href="https://github.com/cobaemon/DBPePro/blob/main/README.md">GitHub: README</a>
        <br>
        　バックエンド: <a href="https://github.com/cobaemon/DBPeProAPI/blob/main/README.md">GitHub: README</a>
        {% endblocktrans %}
    </div>
</div>
{% endblock %}

{% block messege_form %}
{% if form %}
<br><br><br>
<div class="card">
    <div class="card-header bg-dark text-white">
        <h1>{% trans "メッセージ" %}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.email_title }}
            <br><br>
            {{ form.email_message }}
            <br><br>
            <button class="btn btn-dark float-end" type="submit">
                {% trans "送信" %}
            </button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/portfolio/deliverables.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Portfolio - 成果物" %}{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for deliverable in deliverables %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-dark text-white">
                <div class="row">
                    <div class="col">
                        <h1>{{ deliverable.0 }}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <h3>{{ deliverable.1 }}</h3>
                <br>
                <a class="btn btn-dark float-end" role="button"
                   href="{% url deliverable.2 %}">
                    {% trans "見る" %}
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block messege_form %}
{% if form %}
<br><br><br>
<div class="card">
    <div class="card-header bg-dark text-white">
        <h1>{% trans "メッセージ" %}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.email_title }}
            <br><br>
            {{ form.email_message }}
            <br><br>
            <button class="btn btn-dark float-end" type="submit">
                {% trans "送信" %}
            </button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/portfolio/omcen.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Portfolio - Omcen" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h1>Omcen</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        {% blocktrans %}
        〇 なぜ、作ろうと思ったのか
        <br>
        　様々な成果物を公開するにあたって、成果物ごとにアカウントを作るのはユーザに冗長な操作を強いてしまうため
        <br>
        　その解決策として、統合管理するOmcenを作ろうと思いました
        <br><br>
        〇 概要
        <br>
        　Omcenの主な機能としては、アカウントの認証周り・アカウントの管理・サービスの管理を行っています
        <br>
        　ちなみに、Omcenの名前の由来はラテン語で「全ての中心: Omnes centrum」からきています
        <br><br>
        〇 開発環境
        <br>
        　OS: Windows
        <br>
        　言語: Python
        <br>
        　フレームワーク: Django
        <br>
        　DB: PostgreSQL
        <br><br>
        〇 ソースコード: <a href="https://github.com/cobaemon/Omcen/tree/koba">GitHub</a>
        <br>
        〇 完成品: <a href="{{ deliverables_url }}">Omcen</a>
        <br><br>
        〇 工夫
        <br>
        　認証周りにはDjango-allauthを使用することで、自ら実装するよりも短期間でなおかつセキュリティホールのリスクを軽減しました
        <br>
        　さらに、ソーシャルアカウントでのログインにも対応しています
        <br><br>
        〇 利用方法
        <br>
        　Omcenアカウントを作る場合は
        <br>
        　サイト上部の歯車マーク又はこちらから、<a href="{{ signup_url }}">新規登録</a>作ることができます
        {% endblocktrans %}
    </div>
</div>
{% endblock %}

{% block messege_form %}
{% if form %}
<br><br><br>
<div class="card">
    <div class="card-header bg-dark text-white">
        <h1>{% trans "メッセージ" %}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.email_title }}
            <br><br>
            {{ form.email_message }}
            <br><br>
            <button class="btn btn-dark float-end" type="submit">
                {% trans "送信" %}
            </button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/portfolio/password_box.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Portfolio - Password Box" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h1>Password Box</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        {% blocktrans %}
        〇 なぜ、作ろうと思ったのか
        <br>
        　日々インターネットを利用していると、アカウントを作成する機会が多く
        <br>
        　パスワードなどを覚えておくのが大変だったので、
        <br>
        　その解決策として、パスワードをなどのアカウント情報を管理するPassword Boxを作ろうと思いました
        <br><br>
        〇 概要
        <br>
        　Password Boxの主な機能としては、アカウント情報の管理・パスワードの自動生成があります
        <br><br>
        〇 開発環境
        <br>
        　OS: Windows
        <br>
        　言語: Python
        <br>
        　フレームワーク: Django
        <br>
        　DB: PostgreSQL
        <br><br>
        〇 ソースコード: <a href="https://github.com/cobaemon/Omcen/tree/koba/password_box">GitHub</a>
        <br>
        〇 完成品: <a href="{{ deliverables_url }}">Password Box</a>
        <br><br>
        〇 工夫
        <br>
        　アカウント情報の暗号化には共通鍵を使用することで暗号化・復号化時間を短くしています
        <br><br>
        〇 利用方法
        <br>
        　現在Password Boxは、Omcenサービスの一部となっているため
        <br>
        　Omcenアカウントを持っていない又はログインしていない場合は
        <br>
        　サイト上部の歯車マーク又はこちらから、<a href="{{ login_url }}">ログイン</a>または<a href="{{ signup_url }}">新規登録</a>をしてください
        <br><br>
        　次にサービス一覧ページにて利用したいサービスを登録してください
        <br>
        　サービス一覧ページはサイト上部のサービス又はこちらから、<a href="{{ service_list_url }}">サービス一覧</a>
        <br><br>
        　Password Box自体の利用方法は、トップページではボックスの一覧が表示されボックスの検索・新規作成・削除ができます
        <br>
        　ボックスを選択することでボックスの編集ができます
        {% endblocktrans %}
    </div>
</div>
{% endblock %}

{% block messege_form %}
{% if form %}
<br><br><br>
<div class="card">
    <div class="card-header bg-dark text-white">
        <h1>{% trans "メッセージ" %}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.email_title }}
            <br><br>
            {{ form.email_message }}
            <br><br>
            <button class="btn btn-dark float-end" type="submit">
                {% trans "送信" %}
            </button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/portfolio/top.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Portfolio - トップ" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        {% blocktrans %}
        この度は私のポートフォリオに訪問していただき、ありがとうございます
        <br><br><br>
        私は現在プログラミングが好きですし、そうであり続けたいと思っています。
        <br><br>
        私がプログラミングに初めて触れたのは高校生の時です、最初は、何が何だかわかりませんでしたが
        <br>
        基本的な構文を理解し、徐々に自分の考えをプログラミングで表現できるようになりそこに楽しさを感じました。
        <br><br>
        それから高校を卒業し、専門学校に入学して本格的にプログラミングを勉強し始めました。
        <br>
        入学して数か月あたりで、オセロやじゃんけんゲームなどの作りたいものを実際に作れるようになりましたが
        <br>
        作りたいものができてから完成するまで、様々な壁にぶつかりました。
        <br>
        しかし、その壁を乗り越えて完成させたときは達成感でいっぱいになりました。
        <br><br>
        このようなことを繰り返していくうちに、私はプログラミングが好きになりました。
        <br><br><br>
        質問などあれば、いつでもページ下部のメッセージ送信フォームからメッセージをください
        {% endblocktrans %}
    </div>
</div>
{% endblock %}

{% block messege_form %}
{% if form %}
<br><br><br>
<div class="card">
    <div class="card-header bg-dark text-white">
        <h1>{% trans "メッセージ" %}</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.email_title }}
            <br><br>
            {{ form.email_message }}
            <br><br>
            <button class="btn btn-dark float-end" type="submit">
                {% trans "送信" %}
            </button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}