config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('omcen/', include('omcen.urls')),
    path('password box/', include('password_box.urls')),
    path('file encryption/', include('file_encryption.urls')),
    path('tango/', include('tango.urls')),
    path('portfolio/', include('portfolio.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

omcen/urls.py
from django.urls import path

from omcen.views import ServiceControl, CreateService, ServiceList, ServiceSubscribe, PlanSelection, ServiceInUseList, \
    ServiceUnsubscribe, switching_enabled, ServiceDetail, CreatePlan, UpdatePlan, DeletePlan, OmcenUserDeactivate, \
    MyPage, ChangeProfile, LinkingOmcenUsersToSocialAccountsView, LinkedIDPublishing, LinkingUser, Top

app_name = 'Omcen'

urlpatterns = [
    # 管理画面
    path('admin/service_control/', ServiceControl.as_view(), name='service_control'),

    # サービスCRUD
    path('admin/service_detail/<uuid:service_id>/', ServiceDetail.as_view(), name='service_detail'),
    path('admin/create_service', CreateService.as_view(), name='create_service'),
    # path('admin/update_service/<int:pk>', , name='update_service'),
    # path('admin/delete_service/<int:pk>', , name='delete_service'),

    # プランCRUD
    path('admin/create_plan/<uuid:service_id>/', CreatePlan.as_view(), name="create_plan"),
    path('admin/update_plan/<uuid:service_id>/<uuid:pk>/', UpdatePlan.as_view(), name="update_plan"),
    path('admin/delete_plan/<uuid:service_id>/<uuid:pk>/', DeletePlan.as_view(), name="delete_plan"),

    # サービスの有効無効切り替え
    path('admin/switching_enabled/<uuid:service_id>/<uuid:plan_id>/<str:flag>/', switching_enabled,
         name='switching_enabled'),

    # サービス一覧
    path('service_list/', ServiceList.as_view(), name='service_list'),
    # プラン選択
    path('<str:service_name>/plan_selection/', PlanSelection.as_view(), name='plan_selection'),
    # サービス登録
    path('<uuid:pk>/service_subscribe/', ServiceSubscribe.as_view(), name='service_subscribe'),
    # サービス登録解除
    path('<uuid:pk>/service_unsubscribe/', ServiceUnsubscribe.as_view(), name='service_unsubscribe'),
    # 登録中のサービス一覧
    path('service_in_use_list/', ServiceInUseList.as_view(), name='service_in_use_list'),

    # omcenユーザの停止
    path('<uuid:pk>/omcen_user_deactivate/', OmcenUserDeactivate.as_view(), name='omcen_user_deactivate'),
    # マイページ
    path('my_page/', MyPage.as_view(), name='my_page'),
    # プロフィール編集
    path('my_page/<uuid:pk>/change_profile/', ChangeProfile.as_view(), name='change_profile'),
    # 連携ID発行
    path('account_linking/linked_id_publishing/', LinkedIDPublishing.as_view(), name='linked_id_publishing'),
    # ソーシャルアカウントの連携一覧
    path('account_linking/linking_omcen_users_to_social_accounts/', LinkingOmcenUsersToSocialAccountsView.as_view(),
         name='linking_omcen_users_to_social_accounts'),
    # User連携
    path('account_linking/linking_user/', LinkingUser.as_view(), name='linking_user'),
    
    # Top
    path('top/', Top.as_view(), name='top'),
]

portfolio/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from portfolio.views import Top, Profile, Deliverables, VocabularyNotebook, Omcen, PasswordBox, DBPePro

app_name = 'Portfolio'

urlpatterns = [
    path('top/', Top.as_view(), name='top'),
    path('profile/', Profile.as_view(), name='profile'),
    path('deliverables/', Deliverables.as_view(), name='deliverables'),
    path('vocabulary_notebook/', VocabularyNotebook.as_view(), name='vocabulary_notebook'),
    path('omcen/', Omcen.as_view(), name='omcen'),
    path('password_box/', PasswordBox.as_view(), name='password_box'),
    path('dbpepro/', DBPePro.as_view(), name='dbpepro'),
]

tango/urls.py
# -*- coding: utf-8 -*-
"""
Created on 2021/12/05 13:56:15

@author: cobalt
"""

from django.urls import path

from tango.views import TopView, VocabularyNotebookCreateView, VocabularyNotebookDeleteView, \
    VocabularyNotebookUpdateView, VocabularyNotebookReadView, TangoCreateView, TangoReadView, TangoUpdateView, \
    TangoDeleteView

app_name = 'Tango'

urlpatterns = [
    # 単語帳トップページ
    path('top/', TopView.as_view(), name='top'),
    # 単語帳CRUD
    path('vocabulary_notebook_create/', VocabularyNotebookCreateView.as_view(), name='vocabulary_notebook_create'),
    path('<uuid:pk>/vocabulary_notebook_read/', VocabularyNotebookReadView.as_view(), name='vocabulary_notebook_read'),
    path('<uuid:pk>/vocabulary_notebook_update/', VocabularyNotebookUpdateView.as_view(),
         name='vocabulary_notebook_update'),
    path('<uuid:pk>/vocabulary_notebook_delete/', VocabularyNotebookDeleteView.as_view(),
         name='vocabulary_notebook_delete'),
    # 単語CRUD
    path('<uuid:vocabulary_notebook_pk>/tango/tango_create/', TangoCreateView.as_view(), name='tango_create'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_read/', TangoReadView.as_view(), name='tango_read'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_update/', TangoUpdateView.as_view(), name='tango_update'),
    path('<uuid:vocabulary_notebook_pk>/tango/<uuid:pk>/tango_delete/', TangoDeleteView.as_view(), name='tango_delete'),
]

omcen/views.py
import datetime
import uuid as uuid_lib

import pytz
from allauth.socialaccount import providers
from allauth.socialaccount.models import SocialAccount
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView, TemplateView, DeleteView, FormView

from accounts.models import OmcenUser
# from file_encryption.models import FileEncryptionUser
from omcen.forms import SearchService, CreateServiceForm, ServiceSubscribeForm, ServiceUnsubscribeForm, CreatePlanForm, \
    UpdatePlanForm, DeletePlanForm, OmcenUserDeactivateForm, ChangeProfileForm, LinkedIDPublishingForm, LinkingUserForm
from omcen.models import Service, Plan, ServiceGroup, ServiceInUse, LinkingOmcenUsersToSocialAccounts, \
    LinkedID
from password_box.models import PasswordBoxUser, PasswordBox


# サービスの有効・無効切り替え
@login_required
def switching_enabled(request, service_id, plan_id, flag):
    service_group = get_object_or_404(ServiceGroup, service_id=service_id, plan_id=plan_id)
    if flag == 'enabled':
        service_group.is_active = True
        service_group.plan.is_active = True
        messages.success(request, 'サービスを有効にしました。')
    elif flag == 'disabled':
        service_group.is_active = False
        service_group.plan.is_active = False
        messages.success(request, 'サービスを無効にしました。')
    else:
        messages.error(request, 'サービスの有効・無効切り替えに失敗しました。')
        return redirect(reverse_lazy('Omcen:service_detail', args=[service_id]))

    with transaction.atomic():
        service_group.save()
        service_group.plan.save()

    return redirect(reverse_lazy('Omcen:service_detail', args=[service_id]))


# サービス管理画面
class ServiceControl(LoginRequiredMixin, ListView):
    template_name = 'omcen/admin_service_control.html'
    model = Service
    paginate_by = 30
    ordering = 'is_active'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'))
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        form = SearchService(self.request.GET or None)
        query_set = super().get_queryset()

        if form.is_bound:
            if form.is_valid():
                service_name = form.cleaned_data.get('service_name')

                if service_name:
                    query_set = query_set.filter(service_name__icontains=service_name)

            if not query_set.exists():
                messages.info(self.request, '該当するサービスがありませんでした。', extra_tags='info')

        return query_set.order_by('service_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SearchService()

        return context


# サービスの詳細画面
class ServiceDetail(LoginRequiredMixin, TemplateView):
    template_name = 'omcen/admin_service_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        context['plans'] = Plan.objects.filter(service=service)
        context['service'] = service

        return context


# サービスの新規作成
class CreateService(LoginRequiredMixin, CreateView):
    template_name = 'omcen/admin_create_service.html'
    model = ServiceGroup
    form_class = CreateServiceForm
    success_url = reverse_lazy('Omcen:service_control')

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'))
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        # サービスを追加する場合、最低でも1つプランをセットする
        with transaction.atomic():
            service = Service.objects.create(service_name=form.cleaned_data['service_name'])
            plan = Plan.objects.create(service=service,
                                       plan_name=form.cleaned_data['plan_name'],
                                       price=form.cleaned_data['price'])

        if all([service, plan]):
            form.instance.service = service
            form.instance.plan = plan
            form.instance.is_active = False

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def get_success_url(self):
        messages.success(self.request, 'サービスを新しく追加しました。', extra_tags='success')

        return super().get_success_url()


# プランの新規作成
class CreatePlan(LoginRequiredMixin, CreateView):
    template_name = 'omcen/admin_create_plan.html'
    model = Plan
    form_class = CreatePlanForm

    def form_valid(self, form):
        form.instance.service = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service'] = get_object_or_404(Service, pk=self.kwargs.get('service_id'))

        return context

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# プランの編集
class UpdatePlan(LoginRequiredMixin, UpdateView):
    template_name = 'omcen/admin_update_plan.html'
    model = Plan
    form_class = UpdatePlanForm

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# プランの削除
class DeletePlan(LoginRequiredMixin, DeleteView):
    template_name = 'omcen/admin_delete_plan.html'
    model = Plan
    form_class = DeletePlanForm

    def get_success_url(self):
        self.success_url = reverse_lazy('Omcen:service_detail', args=[self.kwargs.get('service_id')])
        return super().get_success_url()


# サービス一覧
class ServiceList(LoginRequiredMixin, ListView):
    template_name = 'omcen/service_list.html'
    model = Service
    paginate_by = 30
    ordering = 'service_name'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        query_set = query_set.filter(is_active=True)

        return query_set.order_by('service_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        services = Service.objects.filter(is_active=True)

        services_dict = {}
        for service in services:
            if ServiceInUse.objects.filter(
                    omcen_user__username=self.request.user,
                    omcen_service__service__service_name=service.service_name
            ).exists():
                services_dict.update({
                    service.service_name: f'{service.service_name}:top'
                })
            else:
                services_dict.update({
                    service.service_name: 'Omcen:plan_selection'
                })

        context['service_dict'] = services_dict

        return context


# プラン選択画面
class PlanSelection(LoginRequiredMixin, ListView):
    template_name = 'omcen/plan_selection.html'
    model = ServiceGroup
    paginate_by = 30
    ordering = 'is_active'
    form = None

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if not Service.objects.filter(service_name=self.request.resolver_match.kwargs['service_name']).exists():
            messages.warning(self.request, _('入力されたサービス名は存在しません'), extra_tags='warning')

            return redirect(to=reverse('Omcen:service_list'))

        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        query_set = super().get_queryset()
        query_set = query_set.filter(
            service__service_name=self.request.resolver_match.kwargs['service_name'],
            is_active=True
        )

        return query_set.order_by('plan__plan_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service_in_use'] = ServiceInUse.objects.filter(
            omcen_user__username=self.request.user,
            omcen_service__service__service_name=self.request.resolver_match.kwargs['service_name'],
            is_active=True
        )

        return context


# サービスの登録
class ServiceSubscribe(LoginRequiredMixin, CreateView):
    template_name = 'omcen/service_subscribe.html'
    model = ServiceInUse
    form_class = ServiceSubscribeForm

    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.warning(self.request, _('ログインしてください'), extra_tags='warning')

            return self.handle_no_permission()

        if ServiceInUse.objects.filter(omcen_user__username=self.request.user,
                                       omcen_service__uuid=self.request.resolver_match.kwargs['pk'],
                                       is_active=True).exists():
            service_in_use = get_object_or_404(
                ServiceInUse,
                omcen_user__username=self.request.user,

templates/omcen/admin_service_detail.html
{% extends 'omcen/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'Omcen:service_control' %}">サービス管理</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ service.service_name }}</li>

{% endblock %}

{% block content %}

<div class="shadow-sm p-3">
    <h3 class="my-3 font-monospace service-title">{{ service.service_name }}</h3>

    <div class="d-flex flex-row-reverse">
        <a class="btn btn-success my-3" href="{% url 'Omcen:create_plan' service.pk %}">プランの新規作成</a>
    </div>


    <table class="table">
        <thead>
        <th width="10%"></th>
        <th width="40%">プラン名</th>
        <th width="10%">価格</th>
        <th width="10%"></th>
        <th width="10%"></th>
        <th width="10%"></th>
        </thead>
        <tbody>
        {% for plan in plans %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ plan.plan_name }}</td>
            <td>{{ plan.price }}</td>
            <td align="right">
                <a class="btn btn-primary" href="{% url 'Omcen:update_plan' plan.service_id plan.pk %}">編集</a>
            </td>
            <td align="right">
                <a class="btn btn-danger" href="{% url 'Omcen:delete_plan' plan.service_id plan.pk %}">削除</a>
            </td>
            <td align="right">
                {% if not plan.is_active %}
                <a class="btn btn-outline-success"
                   href="{% url 'Omcen:switching_enabled' plan.service_id plan.pk 'enabled' %}">有効化</a>
                {% else %}
                <a class="btn btn-outline-secondary"
                   href="{% url 'Omcen:switching_enabled' plan.service_id plan.pk 'disabled' %}">無効化</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</div>


{% endblock %}

templates/omcen/base.html
<!DOCTYPE html>

{% load static %}
{% load i18n %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'google-icons/css/google-icons.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>{% block head_title %}{{ self.page_name }}{% endblock %}</title>
    {% block head_css %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-3 mb-3">
    <div class="container-fluid">
        {% block app_name %}
        <a class="navbar-brand" href="{% url 'Omcen:top' %}">
            <h2>Omcen</h2>
        </a>
        {% endblock %}

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% block nav_item %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Portfolio:top' %}">{% trans "ポートフォリオ" %}</a>
                </li>
                {% endblock %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Omcen:top' %}">{% trans "Omcen" %}</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% trans "サービス" %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown1">
                        <li><a class="dropdown-item" href="{% url 'Password Box:top' %}">
                            {% trans "パスワード管理" %}
                        </a></li>
                        <!--                        <li><a class="dropdown-item" href="{% url 'File Encryption:top' %}">-->
                        <li><a class="dropdown-item" href="#">
                            {% trans "ファイル暗号化 *未実装*" %}
                        </a></li>
                        <li><a class="dropdown-item" href="{% url 'Tango:top' %}">
                            {% trans "単語帳" %}
                        </a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'Omcen:service_list' %}">{% trans "サービス一覧" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'Omcen:service_in_use_list' %}">
                            {% trans "登録中のサービス一覧" %}
                        </a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="material-icons">settings</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown2">
                        <li><a class="dropdown-item" href="{% url 'Omcen:my_page' %}">{% trans "マイページ" %}</a></li>
                        <li><a class="dropdown-item" href="#">{% trans "設定 *未実装*" %}</a></li>
                        <!--                        <li><a class="dropdown-item" href="{% url 'Omcen:linking_omcen_users_to_social_accounts' %}">-->
                        <li><a class="dropdown-item" href="#">
                            {% trans "Omcenアカウントの連携 *未実装*" %}
                        </a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "ログアウト" %}</a></li>
                        <li><a class="dropdown-item text-danger"
                               href="{% url 'Omcen:omcen_user_deactivate' pk=user.uuid %}">
                            {% trans "アカウントの停止" %}</a>
                        </li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account_login' %}">{% trans "ログイン" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_signup' %}">{% trans "新規登録" %}</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container">
    <nav class="my-4" aria-label="breadcrumb">
        <ol class="breadcrumb">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    {% if form.errors %}
    {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ field.label }}
        {{ field.errors }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% block body %}

    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
    {% block messege_form %}
    {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</div>
<br><br>
{% block pagination %}
{% include "omcen/pagination.html" %}
{% endblock %}
<br><br><br><br><br><br><br><br><br><br>
</body>
</html>

templates/omcen/change_profile.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Omcen - プロフィールの編集" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-primary text-white">
        <div class="row">
            <div class="col">
                <h1>{% trans "プロフィールの編集" %}</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        {% if form.errors %}
        {{ form.errors }}
        {% endif %}
        <br>
        <form method="post">
            {% csrf_token %}
            <p>{{ form.username }}</p>
            <p>{{ form.first_name }}</p>
            <p>{{ form.last_name }}</p>
            <p>{{ form.email }}</p>
            <nobr class="float-end">
                <button class="btn btn-warning me-3" type="submit">
                    {% trans "変更" %}
                </button>
                <a class="btn btn-secondary" role="button"
                   href="{% url 'Omcen:my_page' %}">
                    {% trans "キャンセル" %}
                </a>
            </nobr>
        </form>
    </div>
</div>
{% endblock %}

templates/omcen/linking_omcen_users_to_social_accounts.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Omcen - ソーシャルアカウントの連携" %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header p-3 mb-2 bg-success text-white">
        <div class="row">
            <div class="col">
                <h1>{% trans "連携IDの発行" %}</h1>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h2>実装中</h2>
        <a class="btn btn-primary float-end" role="button"
           href="{% url 'Omcen:linked_id_publishing' %}">
            {% trans "発行" %}
        </a>
    </div>
</div>
<br>
<br>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for provider in provider_list %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{{ provider.name }}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <h2>実装中</h2>
                {% if provider.id in linked_provider %}
                <a class="btn btn-danger float-end" role="button"
                   href="#">
                    {% trans "連携解除" %}
                </a>
                {% else %}
                <a class="btn btn-primary float-end" role="button"
                   href="{% url 'Omcen:linking_user' %}">
                    {% trans "連携" %}
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/omcen/plan_selection.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Omcen - プラン選択" %}{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for service_group in object_list %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{{ service_group.service.service_name }}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>{% trans "プラン名" %}: {{ service_group.plan.plan_name }}</p>
                <p>{% trans "価格" %}: {{ service_group.plan.price }}{% trans "円" %}</p>
                {% if service_group.uuid == service_in_use.0.omcen_service.uuid %}
                <p>{% trans "登録中" %}</p>
                <a class="btn btn-danger float-end" role="button"
                   href="{% url 'Omcen:service_unsubscribe' pk=service_in_use.0.uuid %}">
                    {% trans "登録解除" %}
                </a>
                {% else %}
                <a class="btn btn-primary float-end" role="button"
                   href="{% url 'Omcen:service_subscribe' pk=service_group.uuid %}">
                    {% trans "選択" %}
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/omcen/service_list.html
{% extends "omcen/base.html" %}

{% load static %}
{% load i18n %}

{% block head_title %}{% trans "Omcen - サービス一覧" %}{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for service_name, service_url in service_dict.items %}
    <div class="col">
        <div class="card">
            <div class="card-header p-3 mb-2 bg-primary text-white">
                <div class="row">
                    <div class="col">
                        <h1>{{ service_name }}</h1>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {% if service_url == 'Omcen:plan_selection' %}
                <a class="btn btn-primary float-end" role="button"
                   href="{% url service_url service_name=service_name %}">
                    {% trans "選択" %}
                </a>
                {% else %}
                <a class="btn btn-primary float-end" role="button"
                   href="{% url service_url %}">
                    {% trans "選択" %}
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}